// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv is optional - in production, environment variables come from the system environment
// Load dotenv only if available (for local development)
if (typeof require !== "undefined") {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require("dotenv/config");
  } catch {
    // dotenv not available (production), use environment variables directly
  }
}

// Try to use prisma/config if available, otherwise use a simple config object
let config;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { defineConfig } = require("prisma/config");
  config = defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
    },
    datasource: {
      url: process.env["DATABASE_URL"] || "file:./prisma/dev.db",
    },
  });
} catch {
  // prisma/config not available (production), export simple config
  config = {
    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
    },
    datasource: {
      url: process.env["DATABASE_URL"] || "file:./prisma/dev.db",
    },
  };
}

export default config;
